#ifndef TEST_BDRV_SETHB1ACTDRVDETECTINTNODEPTR_HELP_H
#define TEST_BDRV_SETHB1ACTDRVDETECTINTNODEPTR_HELP_H

#include "BDRV_setHB1ActDrvDetectIntNodePtr.h"
#include <stddef.h>
#include <string.h>

#endif /* TEST_BDRV_SETHB1ACTDRVDETECTINTNODEPTR_HELP_H */
