#ifndef TEST_BDRV_SETEXTERNALLS1MOSFETOVERCURRENTINTNODEPTR_HELP_H
#define TEST_BDRV_SETEXTERNALLS1MOSFETOVERCURRENTINTNODEPTR_HELP_H

#include "BDRV_setExternalLS1MosfetOvercurrentIntNodePtr.h"
#include <stddef.h>
#include <string.h>

#endif /* TEST_BDRV_SETEXTERNALLS1MOSFETOVERCURRENTINTNODEPTR_HELP_H */
