#ifndef TEST_BDRV_SETEXTERNALLS2MOSFETOVERCURRENTINTNODEPTR_HELP_H
#define TEST_BDRV_SETEXTERNALLS2MOSFETOVERCURRENTINTNODEPTR_HELP_H

#include "BDRV_setExternalLS2MosfetOvercurrentIntNodePtr.h"
#include <stddef.h>
#include <string.h>

#endif /* TEST_BDRV_SETEXTERNALLS2MOSFETOVERCURRENTINTNODEPTR_HELP_H */
