#ifndef TEST_PMU_SETVDDEXTUNDERVOLTAGEINTNODEPTR_HELP_H
#define TEST_PMU_SETVDDEXTUNDERVOLTAGEINTNODEPTR_HELP_H

#include "PMU_setVDDEXTUndervoltageIntNodePtr.h"
#include <stddef.h>
#include <string.h>

#endif /* TEST_PMU_SETVDDEXTUNDERVOLTAGEINTNODEPTR_HELP_H */
