#ifndef TEST_BDRV_SETHB2ADAPTSEQINTNODEPTR_HELP_H
#define TEST_BDRV_SETHB2ADAPTSEQINTNODEPTR_HELP_H

#include "BDRV_setHB2AdaptSeqIntNodePtr.h"
#include <stddef.h>
#include <string.h>

#endif /* TEST_BDRV_SETHB2ADAPTSEQINTNODEPTR_HELP_H */
