/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_system_tle989x.h"

static const char* CMockString_SystemInit = "SystemInit";

typedef struct _CMOCK_SystemInit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;

} CMOCK_SystemInit_CALL_INSTANCE;

static struct mock_system_tle989xInstance
{
  char SystemInit_IgnoreBool;
  char SystemInit_CallbackBool;
  CMOCK_SystemInit_CALLBACK SystemInit_CallbackFunctionPointer;
  int SystemInit_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE SystemInit_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_system_tle989x_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.SystemInit_CallInstance;
  if (Mock.SystemInit_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SystemInit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.SystemInit_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_system_tle989x_Init(void)
{
  mock_system_tle989x_Destroy();
}

void mock_system_tle989x_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

void SystemInit(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SystemInit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SystemInit);
  cmock_call_instance = (CMOCK_SystemInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SystemInit_CallInstance);
  Mock.SystemInit_CallInstance = CMock_Guts_MemNext(Mock.SystemInit_CallInstance);
  if (Mock.SystemInit_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.SystemInit_CallbackBool &&
      Mock.SystemInit_CallbackFunctionPointer != NULL)
  {
    Mock.SystemInit_CallbackFunctionPointer(Mock.SystemInit_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.SystemInit_CallbackFunctionPointer != NULL)
  {
    Mock.SystemInit_CallbackFunctionPointer(Mock.SystemInit_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void SystemInit_CMockIgnore(void)
{
  Mock.SystemInit_IgnoreBool = (char)1;
}

void SystemInit_CMockStopIgnore(void)
{
  Mock.SystemInit_IgnoreBool = (char)0;
}

void SystemInit_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SystemInit_CALL_INSTANCE));
  CMOCK_SystemInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_SystemInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SystemInit_CallInstance = CMock_Guts_MemChain(Mock.SystemInit_CallInstance, cmock_guts_index);
  Mock.SystemInit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void SystemInit_AddCallback(CMOCK_SystemInit_CALLBACK Callback)
{
  Mock.SystemInit_IgnoreBool = (char)0;
  Mock.SystemInit_CallbackBool = (char)1;
  Mock.SystemInit_CallbackFunctionPointer = Callback;
}

void SystemInit_Stub(CMOCK_SystemInit_CALLBACK Callback)
{
  Mock.SystemInit_IgnoreBool = (char)0;
  Mock.SystemInit_CallbackBool = (char)0;
  Mock.SystemInit_CallbackFunctionPointer = Callback;
}

