/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_SYSTEM_TLE989X_H
#define _MOCK_SYSTEM_TLE989X_H

#include "unity.h"
#include "system_tle989x.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_system_tle989x_Init(void);
void mock_system_tle989x_Destroy(void);
void mock_system_tle989x_Verify(void);




#define SystemInit_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("SystemInit requires _Ignore (not AndReturn)");
#define SystemInit_Ignore() SystemInit_CMockIgnore()
void SystemInit_CMockIgnore(void);
#define SystemInit_StopIgnore() SystemInit_CMockStopIgnore()
void SystemInit_CMockStopIgnore(void);
#define SystemInit_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("SystemInit requires _Expect (not AndReturn)");
#define SystemInit_Expect() SystemInit_CMockExpect(__LINE__)
void SystemInit_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_SystemInit_CALLBACK)(int cmock_num_calls);
void SystemInit_AddCallback(CMOCK_SystemInit_CALLBACK Callback);
void SystemInit_Stub(CMOCK_SystemInit_CALLBACK Callback);
#define SystemInit_StubWithCallback SystemInit_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
