/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_cantrx.h"

static const char* CMockString_CANTRX_init = "CANTRX_init";

typedef struct _CMOCK_CANTRX_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  sint8 ReturnVal;
  int CallOrder;

} CMOCK_CANTRX_init_CALL_INSTANCE;

static struct mock_cantrxInstance
{
  char CANTRX_init_IgnoreBool;
  sint8 CANTRX_init_FinalReturn;
  char CANTRX_init_CallbackBool;
  CMOCK_CANTRX_init_CALLBACK CANTRX_init_CallbackFunctionPointer;
  int CANTRX_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE CANTRX_init_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_cantrx_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.CANTRX_init_CallInstance;
  if (Mock.CANTRX_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_CANTRX_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.CANTRX_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_cantrx_Init(void)
{
  mock_cantrx_Destroy();
}

void mock_cantrx_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

sint8 CANTRX_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_CANTRX_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_CANTRX_init);
  cmock_call_instance = (CMOCK_CANTRX_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.CANTRX_init_CallInstance);
  Mock.CANTRX_init_CallInstance = CMock_Guts_MemNext(Mock.CANTRX_init_CallInstance);
  if (Mock.CANTRX_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.CANTRX_init_FinalReturn;
    memcpy((void*)(&Mock.CANTRX_init_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(sint8[sizeof(cmock_call_instance->ReturnVal) == sizeof(sint8) ? 1 : -1])); /* add sint8 to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.CANTRX_init_CallbackBool &&
      Mock.CANTRX_init_CallbackFunctionPointer != NULL)
  {
    sint8 cmock_cb_ret = Mock.CANTRX_init_CallbackFunctionPointer(Mock.CANTRX_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.CANTRX_init_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.CANTRX_init_CallbackFunctionPointer(Mock.CANTRX_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CANTRX_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, sint8 cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_CANTRX_init_CALL_INSTANCE));
  CMOCK_CANTRX_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_CANTRX_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.CANTRX_init_CallInstance = CMock_Guts_MemChain(Mock.CANTRX_init_CallInstance, cmock_guts_index);
  Mock.CANTRX_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.CANTRX_init_IgnoreBool = (char)1;
}

void CANTRX_init_CMockStopIgnore(void)
{
  if(Mock.CANTRX_init_IgnoreBool)
    Mock.CANTRX_init_CallInstance = CMock_Guts_MemNext(Mock.CANTRX_init_CallInstance);
  Mock.CANTRX_init_IgnoreBool = (char)0;
}

void CANTRX_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sint8 cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_CANTRX_init_CALL_INSTANCE));
  CMOCK_CANTRX_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_CANTRX_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.CANTRX_init_CallInstance = CMock_Guts_MemChain(Mock.CANTRX_init_CallInstance, cmock_guts_index);
  Mock.CANTRX_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(sint8[sizeof(cmock_to_return) == sizeof(sint8) ? 1 : -1])); /* add sint8 to :treat_as_array if this causes an error */
}

void CANTRX_init_AddCallback(CMOCK_CANTRX_init_CALLBACK Callback)
{
  Mock.CANTRX_init_IgnoreBool = (char)0;
  Mock.CANTRX_init_CallbackBool = (char)1;
  Mock.CANTRX_init_CallbackFunctionPointer = Callback;
}

void CANTRX_init_Stub(CMOCK_CANTRX_init_CALLBACK Callback)
{
  Mock.CANTRX_init_IgnoreBool = (char)0;
  Mock.CANTRX_init_CallbackBool = (char)0;
  Mock.CANTRX_init_CallbackFunctionPointer = Callback;
}

