/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_CANTRX_H
#define _MOCK_CANTRX_H

#include "unity.h"
#include "cantrx.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_cantrx_Init(void);
void mock_cantrx_Destroy(void);
void mock_cantrx_Verify(void);




#define CANTRX_init_Ignore() TEST_FAIL_MESSAGE("CANTRX_init requires _IgnoreAndReturn");
#define CANTRX_init_IgnoreAndReturn(cmock_retval) CANTRX_init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void CANTRX_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, sint8 cmock_to_return);
#define CANTRX_init_StopIgnore() CANTRX_init_CMockStopIgnore()
void CANTRX_init_CMockStopIgnore(void);
#define CANTRX_init_Expect() TEST_FAIL_MESSAGE("CANTRX_init requires _ExpectAndReturn");
#define CANTRX_init_ExpectAndReturn(cmock_retval) CANTRX_init_CMockExpectAndReturn(__LINE__, cmock_retval)
void CANTRX_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, sint8 cmock_to_return);
typedef sint8 (* CMOCK_CANTRX_init_CALLBACK)(int cmock_num_calls);
void CANTRX_init_AddCallback(CMOCK_CANTRX_init_CALLBACK Callback);
void CANTRX_init_Stub(CMOCK_CANTRX_init_CALLBACK Callback);
#define CANTRX_init_StubWithCallback CANTRX_init_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
