#ifndef TEST_BDRV_SETEXTERNALHS3MOSFETOVERCURRENTINTNODEPTR_HELP_H
#define TEST_BDRV_SETEXTERNALHS3MOSFETOVERCURRENTINTNODEPTR_HELP_H

#include "BDRV_setExternalHS3MosfetOvercurrentIntNodePtr.h"
#include <stddef.h>
#include <string.h>

#endif /* TEST_BDRV_SETEXTERNALHS3MOSFETOVERCURRENTINTNODEPTR_HELP_H */
