#ifndef TEST_SDADC_SETCH0CMPUPINTNODEPTR_HELP_H
#define TEST_SDADC_SETCH0CMPUPINTNODEPTR_HELP_H

#include "SDADC_setCh0CmpUpIntNodePtr.h"
#include <stddef.h>
#include <string.h>

#endif /* TEST_SDADC_SETCH0CMPUPINTNODEPTR_HELP_H */
