#ifndef TEST_PMU_SETVDDPUNDERVOLTAGEWARNINTNODEPTR_HELP_H
#define TEST_PMU_SETVDDPUNDERVOLTAGEWARNINTNODEPTR_HELP_H

#include "PMU_setVDDPUndervoltageWarnIntNodePtr.h"
#include <stddef.h>
#include <string.h>

#endif /* TEST_PMU_SETVDDPUNDERVOLTAGEWARNINTNODEPTR_HELP_H */
