#ifndef TEST_SSC1_SETEMPTYTXBUFFERINTNODEPTR_HELP_H
#define TEST_SSC1_SETEMPTYTXBUFFERINTNODEPTR_HELP_H

#include "SSC1_setEmptyTXBufferIntNodePtr.h"
#include <stddef.h>
#include <string.h>

#endif /* TEST_SSC1_SETEMPTYTXBUFFERINTNODEPTR_HELP_H */
