#ifndef TEST_PMU_SETVDDCUNDERVOLTAGEWARNINTNODEPTR_HELP_H
#define TEST_PMU_SETVDDCUNDERVOLTAGEWARNINTNODEPTR_HELP_H

#include "PMU_setVDDCUndervoltageWarnIntNodePtr.h"
#include <stddef.h>
#include <string.h>

#endif /* TEST_PMU_SETVDDCUNDERVOLTAGEWARNINTNODEPTR_HELP_H */
