#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

#define RTE_DEVICE_TLELIB_PMU
#define RTE_DEVICE_TLELIB_BOOTROM
#define RTE_DEVICE_TLELIB_ISR
#define RTE_DEVICE_TLELIB_GPIO

#endif /* RTE_COMPONENTS_H */