#ifndef TEST_PMU_SETVDDPOVERVOLTAGEINTNODEPTR_HELP_H
#define TEST_PMU_SETVDDPOVERVOLTAGEINTNODEPTR_HELP_H

#include "PMU_setVDDPOvervoltageIntNodePtr.h"
#include <stddef.h>
#include <string.h>

#endif /* TEST_PMU_SETVDDPOVERVOLTAGEINTNODEPTR_HELP_H */
