#ifndef TEST_SDADC_SETCH0CMPLOINTNODEPTR_HELP_H
#define TEST_SDADC_SETCH0CMPLOINTNODEPTR_HELP_H

#include "SDADC_setCh0CmpLoIntNodePtr.h"
#include <stddef.h>
#include <string.h>

#endif /* TEST_SDADC_SETCH0CMPLOINTNODEPTR_HELP_H */
