/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_cantrx.h"

static const char* CMockString_CANTRX_setCANTRXIntNodePtr = "CANTRX_setCANTRXIntNodePtr";

typedef struct _CMOCK_CANTRX_setCANTRXIntNodePtr_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;

} CMOCK_CANTRX_setCANTRXIntNodePtr_CALL_INSTANCE;

static struct mock_cantrxInstance
{
  char CANTRX_setCANTRXIntNodePtr_IgnoreBool;
  char CANTRX_setCANTRXIntNodePtr_CallbackBool;
  CMOCK_CANTRX_setCANTRXIntNodePtr_CALLBACK CANTRX_setCANTRXIntNodePtr_CallbackFunctionPointer;
  int CANTRX_setCANTRXIntNodePtr_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE CANTRX_setCANTRXIntNodePtr_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_cantrx_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.CANTRX_setCANTRXIntNodePtr_CallInstance;
  if (Mock.CANTRX_setCANTRXIntNodePtr_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_CANTRX_setCANTRXIntNodePtr);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.CANTRX_setCANTRXIntNodePtr_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_cantrx_Init(void)
{
  mock_cantrx_Destroy();
}

void mock_cantrx_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

void CANTRX_setCANTRXIntNodePtr(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_CANTRX_setCANTRXIntNodePtr_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_CANTRX_setCANTRXIntNodePtr);
  cmock_call_instance = (CMOCK_CANTRX_setCANTRXIntNodePtr_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.CANTRX_setCANTRXIntNodePtr_CallInstance);
  Mock.CANTRX_setCANTRXIntNodePtr_CallInstance = CMock_Guts_MemNext(Mock.CANTRX_setCANTRXIntNodePtr_CallInstance);
  if (Mock.CANTRX_setCANTRXIntNodePtr_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.CANTRX_setCANTRXIntNodePtr_CallbackBool &&
      Mock.CANTRX_setCANTRXIntNodePtr_CallbackFunctionPointer != NULL)
  {
    Mock.CANTRX_setCANTRXIntNodePtr_CallbackFunctionPointer(Mock.CANTRX_setCANTRXIntNodePtr_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.CANTRX_setCANTRXIntNodePtr_CallbackFunctionPointer != NULL)
  {
    Mock.CANTRX_setCANTRXIntNodePtr_CallbackFunctionPointer(Mock.CANTRX_setCANTRXIntNodePtr_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CANTRX_setCANTRXIntNodePtr_CMockIgnore(void)
{
  Mock.CANTRX_setCANTRXIntNodePtr_IgnoreBool = (char)1;
}

void CANTRX_setCANTRXIntNodePtr_CMockStopIgnore(void)
{
  Mock.CANTRX_setCANTRXIntNodePtr_IgnoreBool = (char)0;
}

void CANTRX_setCANTRXIntNodePtr_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_CANTRX_setCANTRXIntNodePtr_CALL_INSTANCE));
  CMOCK_CANTRX_setCANTRXIntNodePtr_CALL_INSTANCE* cmock_call_instance = (CMOCK_CANTRX_setCANTRXIntNodePtr_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.CANTRX_setCANTRXIntNodePtr_CallInstance = CMock_Guts_MemChain(Mock.CANTRX_setCANTRXIntNodePtr_CallInstance, cmock_guts_index);
  Mock.CANTRX_setCANTRXIntNodePtr_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void CANTRX_setCANTRXIntNodePtr_AddCallback(CMOCK_CANTRX_setCANTRXIntNodePtr_CALLBACK Callback)
{
  Mock.CANTRX_setCANTRXIntNodePtr_IgnoreBool = (char)0;
  Mock.CANTRX_setCANTRXIntNodePtr_CallbackBool = (char)1;
  Mock.CANTRX_setCANTRXIntNodePtr_CallbackFunctionPointer = Callback;
}

void CANTRX_setCANTRXIntNodePtr_Stub(CMOCK_CANTRX_setCANTRXIntNodePtr_CALLBACK Callback)
{
  Mock.CANTRX_setCANTRXIntNodePtr_IgnoreBool = (char)0;
  Mock.CANTRX_setCANTRXIntNodePtr_CallbackBool = (char)0;
  Mock.CANTRX_setCANTRXIntNodePtr_CallbackFunctionPointer = Callback;
}

