/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_CANTRX_H
#define _MOCK_CANTRX_H

#include "unity.h"
#include "cantrx.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_cantrx_Init(void);
void mock_cantrx_Destroy(void);
void mock_cantrx_Verify(void);




#define CANTRX_setCANTRXIntNodePtr_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("CANTRX_setCANTRXIntNodePtr requires _Ignore (not AndReturn)");
#define CANTRX_setCANTRXIntNodePtr_Ignore() CANTRX_setCANTRXIntNodePtr_CMockIgnore()
void CANTRX_setCANTRXIntNodePtr_CMockIgnore(void);
#define CANTRX_setCANTRXIntNodePtr_StopIgnore() CANTRX_setCANTRXIntNodePtr_CMockStopIgnore()
void CANTRX_setCANTRXIntNodePtr_CMockStopIgnore(void);
#define CANTRX_setCANTRXIntNodePtr_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("CANTRX_setCANTRXIntNodePtr requires _Expect (not AndReturn)");
#define CANTRX_setCANTRXIntNodePtr_Expect() CANTRX_setCANTRXIntNodePtr_CMockExpect(__LINE__)
void CANTRX_setCANTRXIntNodePtr_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_CANTRX_setCANTRXIntNodePtr_CALLBACK)(int cmock_num_calls);
void CANTRX_setCANTRXIntNodePtr_AddCallback(CMOCK_CANTRX_setCANTRXIntNodePtr_CALLBACK Callback);
void CANTRX_setCANTRXIntNodePtr_Stub(CMOCK_CANTRX_setCANTRXIntNodePtr_CALLBACK Callback);
#define CANTRX_setCANTRXIntNodePtr_StubWithCallback CANTRX_setCANTRXIntNodePtr_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
