/**
 * @file Mcu.h
 * @brief Public interface for MCU initialization and basic MCU services.
 *
 * This module provides the public APIs used to initialize the MCU-related
 * hardware services and to manage basic runtime functions such as watchdog
 * servicing and system time handling.
 *
 * The implementation initializes the hardware modules through the device
 * configuration generated by the Config Wizard, clears fail-safe watchdog
 * status information, releases the safe shutdown mechanism, services the
 * watchdog trigger registers, reloads the SysTick counter, and provides the
 * current system time in milliseconds.
 */

#ifndef MCU_H
#define MCU_H

/*==============================================================================
 * Includes
 *============================================================================*/

/**
 * @brief Standard integer type definitions.
 *
 * Required for the fixed-width integer types used by this module interface.
 */
#include <stdint.h>

/*==============================================================================
 * Public function prototypes
 *============================================================================*/

/**
 * @brief Initialize the MCU-related hardware services.
 *
 * This function performs the MCU startup initialization sequence handled by this
 * module.
 *
 * The implementation performs the following actions:
 * - Clears the fail-safe watchdog fail status.
 * - Initializes the hardware modules according to the Config Wizard setup.
 * - Clears fail-safe and safe shutdown status registers to release the safe
 *   shutdown mechanism.
 *
 * @pre The low-level device registers and startup environment shall be available.
 *
 * @post The configured hardware modules are initialized.
 * @post The fail-safe watchdog fail status is cleared.
 * @post The safe shutdown mechanism is released when all related status bits are
 *       cleared.
 *
 * @return None.
 */
void Mcu_Initialize(void);

/**
 * @brief Service the main fail-safe watchdog.
 *
 * This function services the watchdog by toggling the watchdog trigger bit.
 *
 * It shall be called periodically within the allowed watchdog service window.
 * Based on the current configuration, the expected call period is between
 * 19.2 ms and 27.2 ms.
 *
 * @pre Mcu_Initialize() shall have been executed before this function is used
 *      in normal runtime operation.
 *
 * @post The main watchdog trigger bit is toggled.
 *
 * @return None.
 */
void Mcu_ServiceWatchdog(void);

/**
 * @brief Service the safe operating window watchdog.
 *
 * This function services the safe operating window watchdog by toggling the
 * corresponding trigger bit.
 *
 * @pre Mcu_Initialize() shall have been executed before this function is used
 *      in normal runtime operation.
 *
 * @post The safe operating window watchdog trigger bit is toggled.
 *
 * @return None.
 */
void Mcu_ServiceWatchdogSow(void);

/**
 * @brief Reload the SysTick counter and reset the module timestamp.
 *
 * This function resets the current SysTick counter value and clears the global
 * millisecond timestamp used by Mcu_GetSystemTime_u32().
 *
 * @pre The CPU SysTick register interface shall be available.
 *
 * @post The SysTick current value register is reset to 0.
 * @post The global millisecond timestamp is reset to 0.
 *
 * @return None.
 */

/**
 * @brief Get the current system time in milliseconds.
 *
 * This function returns the current value of the global millisecond timestamp.
 *
 * @pre The timestamp variable shall be updated by the system time base.
 *
 * @return Current system time in milliseconds.
 */
uint32_t Mcu_GetSystemTime_u32(void);

/*==============================================================================
 * Example code
 *============================================================================*/

/**
 * @brief Toggle the example LED output.
 *
 * This function toggles the state of GPIO P0.6.
 *
 * @note This function is example code and shall not be used as production API
 *       unless it is intentionally kept as part of the final design.
 *
 * @return None.
 */
void toggle_led(void);

#endif /* MCU_H */
