#ifndef TEST_BDRV_SETEXTERNALHS1MOSFETOVERCURRENTINTNODEPTR_HELP_H
#define TEST_BDRV_SETEXTERNALHS1MOSFETOVERCURRENTINTNODEPTR_HELP_H

#include "BDRV_setExternalHS1MosfetOvercurrentIntNodePtr.h"
#include <stddef.h>
#include <string.h>

#endif /* TEST_BDRV_SETEXTERNALHS1MOSFETOVERCURRENTINTNODEPTR_HELP_H */
