#ifndef TEST_BDRV_SETHB3ADAPTSEQINTNODEPTR_HELP_H
#define TEST_BDRV_SETHB3ADAPTSEQINTNODEPTR_HELP_H

#include "BDRV_setHB3AdaptSeqIntNodePtr.h"
#include <stddef.h>
#include <string.h>

#endif /* TEST_BDRV_SETHB3ADAPTSEQINTNODEPTR_HELP_H */
