#ifndef TEST_ADC1_SETSEQ1WAITFORREADINTNODEPTR_HELP_H
#define TEST_ADC1_SETSEQ1WAITFORREADINTNODEPTR_HELP_H

#include "ADC1_setSeq1WaitForReadIntNodePtr.h"
#include <stddef.h>
#include <string.h>

#endif /* TEST_ADC1_SETSEQ1WAITFORREADINTNODEPTR_HELP_H */
