#ifndef TEST_SSC0_SETEMPTYTXBUFFERINTNODEPTR_HELP_H
#define TEST_SSC0_SETEMPTYTXBUFFERINTNODEPTR_HELP_H

#include "SSC0_setEmptyTXBufferIntNodePtr.h"
#include <stddef.h>
#include <string.h>

#endif /* TEST_SSC0_SETEMPTYTXBUFFERINTNODEPTR_HELP_H */
