/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "CANTRX_init.h"
#include "unity.h"
#include "mock_RTE_Components.h"
#include "mock_cantrx_defines.h"
#include "mock_cantrx.h"
#include "mock_cmsis_compiler.h"
#include "mock_cmsis_gcc.h"
#include "mock_cmsis_misra.h"
#include "mock_cmsis_version.h"
#include "mock_core_cm3.h"
#include "mock_error_codes.h"
#include "mock_system_tle989x.h"
#include "mock_tle989x.h"
#include "mock_types.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_CANTRX_init(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
  mock_RTE_Components_Init();
  mock_cantrx_defines_Init();
  mock_cantrx_Init();
  mock_cmsis_compiler_Init();
  mock_cmsis_gcc_Init();
  mock_cmsis_misra_Init();
  mock_cmsis_version_Init();
  mock_core_cm3_Init();
  mock_error_codes_Init();
  mock_system_tle989x_Init();
  mock_tle989x_Init();
  mock_types_Init();
}
static void CMock_Verify(void)
{
  mock_RTE_Components_Verify();
  mock_cantrx_defines_Verify();
  mock_cantrx_Verify();
  mock_cmsis_compiler_Verify();
  mock_cmsis_gcc_Verify();
  mock_cmsis_misra_Verify();
  mock_cmsis_version_Verify();
  mock_core_cm3_Verify();
  mock_error_codes_Verify();
  mock_system_tle989x_Verify();
  mock_tle989x_Verify();
  mock_types_Verify();
}
static void CMock_Destroy(void)
{
  mock_RTE_Components_Destroy();
  mock_cantrx_defines_Destroy();
  mock_cantrx_Destroy();
  mock_cmsis_compiler_Destroy();
  mock_cmsis_gcc_Destroy();
  mock_cmsis_misra_Destroy();
  mock_cmsis_version_Destroy();
  mock_core_cm3_Destroy();
  mock_error_codes_Destroy();
  mock_system_tle989x_Destroy();
  mock_tle989x_Destroy();
  mock_types_Destroy();
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_CANTRX_init_1.c");
  run_test(test_CANTRX_init, "test_CANTRX_init", 2);

  CMock_Guts_MemFreeFinal();
  return UNITY_END();
}
