#ifndef TEST_SSC1_SETEMPTYRXBUFFERINTNODEPTR_HELP_H
#define TEST_SSC1_SETEMPTYRXBUFFERINTNODEPTR_HELP_H

#include "SSC1_setEmptyRXBufferIntNodePtr.h"
#include <stddef.h>
#include <string.h>

#endif /* TEST_SSC1_SETEMPTYRXBUFFERINTNODEPTR_HELP_H */
