#ifndef TEST_BDRV_SETHB1ADAPTSEQINTNODEPTR_HELP_H
#define TEST_BDRV_SETHB1ADAPTSEQINTNODEPTR_HELP_H

#include "BDRV_setHB1AdaptSeqIntNodePtr.h"
#include <stddef.h>
#include <string.h>

#endif /* TEST_BDRV_SETHB1ADAPTSEQINTNODEPTR_HELP_H */
