#ifndef TEST_BDRV_SETEXTERNALHS2MOSFETOVERCURRENTINTNODEPTR_HELP_H
#define TEST_BDRV_SETEXTERNALHS2MOSFETOVERCURRENTINTNODEPTR_HELP_H

#include "BDRV_setExternalHS2MosfetOvercurrentIntNodePtr.h"
#include <stddef.h>
#include <string.h>

#endif /* TEST_BDRV_SETEXTERNALHS2MOSFETOVERCURRENTINTNODEPTR_HELP_H */
