#ifndef TEST_BDRV_SETEXTERNALLS3MOSFETOVERCURRENTINTNODEPTR_HELP_H
#define TEST_BDRV_SETEXTERNALLS3MOSFETOVERCURRENTINTNODEPTR_HELP_H

#include "BDRV_setExternalLS3MosfetOvercurrentIntNodePtr.h"
#include <stddef.h>
#include <string.h>

#endif /* TEST_BDRV_SETEXTERNALLS3MOSFETOVERCURRENTINTNODEPTR_HELP_H */
